# Docker Compose Override for iREVA Platform Development
# This file automatically extends docker-compose.yml for development

version: "3.9"

services:
  backend:
    # Development overrides
    environment:
      - LOG_LEVEL=debug
      - ENABLE_CORS=true
      - ENABLE_SWAGGER=true
    volumes:
      # Enable hot reload for development
      - ./server:/app/server:delegated
      - ./shared:/app/shared:delegated
    command: ["npm", "run", "dev"]

  frontend:
    # Use development build for hot reload
    build:
      target: development
    volumes:
      - ./client:/app/client:delegated
      - ./shared:/app/shared:delegated
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_ENABLE_DEVTOOLS=true

  postgres:
    # Development database settings
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_LOG_STATEMENT=all
    volumes:
      # Persist data and add init scripts
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    # Expose Redis for development tools
    ports:
      - "6379:6379"
    command: redis-server --loglevel verbose

volumes:
  postgres_dev_data: