version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ireva_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_db_password}
      POSTGRES_DB: ireva

  redis:
    image: redis:7
    restart: always

volumes:
  db_data: