version: '3.8'

services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    volumes:
      - ./redis/master.conf:/usr/local/etc/redis/redis.conf
      - redis_master_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  redis-replica-1:
    image: redis:7-alpine
    container_name: redis-replica-1
    volumes:
      - ./redis/replica.conf:/usr/local/etc/redis/redis.conf
      - redis_replica1_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis-master
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  redis-replica-2:
    image: redis:7-alpine
    container_name: redis-replica-2
    volumes:
      - ./redis/replica.conf:/usr/local/etc/redis/redis.conf
      - redis_replica2_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis-master
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis_network
    deploy:
      resources:
        limits:
          memory: 128M

  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis_network
    deploy:
      resources:
        limits:
          memory: 128M

  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis_network
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  redis_network:
    driver: bridge

volumes:
  redis_master_data:
  redis_replica1_data:
  redis_replica2_data: