# iREVA Platform - Render.com Deployment Configuration
# This file configures secure HTTPS deployment on Render with proper environment setup

services:
  # Main Application Service
  - type: web
    name: ireva-platform
    env: node
    plan: starter # Upgrade to standard/pro for production
    region: oregon # Choose region closest to your users
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    
    # Environment Variables (Set these in Render Dashboard)
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 5000
        
      # Database Configuration
      - key: DATABASE_URL
        fromDatabase:
          name: ireva-db
          property: connectionString
      
      # Security Keys (Set these as secret environment variables)
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
        
      - key: SESSION_SECRET
        generateValue: true
        
      - key: JWT_REFRESH_SECRET
        generateValue: true
      
      # CORS Configuration for HTTPS
      - key: CORS_ORIGIN
        value: https://ireva-platform.onrender.com,https://www.ireva.ng
      
      # Frontend URL (Update with your custom domain)
      - key: FRONTEND_URL
        value: https://ireva-platform.onrender.com
        
      - key: BACKEND_URL
        value: https://ireva-platform.onrender.com/api
      
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000 # 15 minutes
        
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      
      # Security Features
      - key: ENABLE_AUDIT_LOGGING
        value: true
        
      - key: ENABLE_EMAIL_VERIFICATION
        value: true
      
      # Logging
      - key: LOG_LEVEL
        value: info
    
    # Auto-deploy from main branch
    autoDeploy: true
    
    # Health check configuration
    healthCheckGracePeriodSeconds: 30
    healthCheckIntervalSeconds: 30
    healthCheckTimeoutSeconds: 10
    
    # Custom domains (configure these after deployment)
    # domains:
    #   - ireva.ng
    #   - www.ireva.ng

  # PostgreSQL Database
  - type: pgsql
    name: ireva-db
    plan: starter # Upgrade to standard/pro for production
    region: oregon
    databaseName: ireva_production
    databaseUser: ireva_user
    
    # Automatic backups
    ipAllowList: [] # Empty means allow all IPs (configure specific IPs for security)

# Background Services (Optional - for future scaling)
# - type: worker
#   name: ireva-background-worker
#   env: node
#   buildCommand: npm ci
#   startCommand: npm run worker
#   envVarsFrom:
#     - service: ireva-platform

# Redis Cache (Optional - for session storage and caching)
# - type: redis
#   name: ireva-cache
#   plan: starter
#   region: oregon
#   ipAllowList: []