services:
  # Define PostgreSQL FIRST
  - type: postgres
    name: iREVA-db    # Must match the name in "fromService"
    region: oregon
    plan: free

  # Define Redis NEXT
  - type: redis
    name: iREVA-redis
    region: oregon
    plan: free

  # Frontend Service
  - type: web
    name: iREVA-frontend
    env: docker
    repo: https://github.com/your-username/ireva
    region: oregon
    dockerContext: ./apps/client
    dockerfilePath: ./apps/client/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://ireva-backend.onrender.com/api

  # Backend Service (comes AFTER database/redis)
  - type: web
    name: iREVA-backend
    env: docker
    repo: https://github.com/your-username/ireva
    region: oregon
    dockerContext: ./apps/server
    dockerfilePath: ./apps/server/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        fromService:
          name: iREVA-db      # Must match the PostgreSQL service name
          type: postgres      # Lowercase
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: iREVA-redis   # Must match the Redis service name
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true   # Let Render generate this
      - key: NODE_ENV
        value: production