services:
  - type: web
    name: iREVA-frontend
    env: docker
    repo: https://github.com/oneroskilfu/ireva-app
    region: oregon
    dockerContext: ./apps/client
    dockerfilePath: ./apps/client/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://ireva-backend.onrender.com/api

  - type: web
    name: iREVA-backend
    env: docker
    repo: https://github.com/oneroskilfu/ireva-app
    region: oregon
    dockerContext: ./apps/server
    dockerfilePath: ./apps/server/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iREVA-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: iREVA-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        value: fba4762e52ab29cbec388fd6908192ab6e836d16baa10bd720ceffcf19627c24119eb6a4b70da2ee85eba036da5d003d3f94bcf06266b48df7681823a174240e
      - key: NODE_ENV
        value: production

  - type: postgres
    name: iREVA-db
    region: oregon
    plan: free

  - type: redis
    name: iREVA-redis
    region: oregon
    plan: free