services:
  - type: web
    name: iREVA-frontend
    env: docker
    repo: https://github.com/your-username/ireva
    region: oregon
    dockerContext: ./apps/client
    dockerfilePath: ./apps/client/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://ireva-backend.onrender.com/api

  - type: web
    name: iREVA-backend
    env: docker
    repo: https://github.com/your-username/ireva
    region: oregon
    dockerContext: ./apps/server
    dockerfilePath: ./apps/server/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: iREVA-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: iREVA-redis
          property: connectionString
      - key: JWT_SECRET
        value: your-secret-key
      - key: NODE_ENV
        value: production

  - type: postgres
    name: iREVA-db
    region: oregon
    plan: free

  - type: redis
    name: iREVA-redis
    region: oregon
    plan: free