services:
  - type: web
    name: iREVA-frontend
    env: docker
    repo: https://github.com/oneroskilfu/ireva-app
    region: oregon
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://ireva-backend.onrender.com/api

  - type: web
    name: iREVA-backend
    env: docker
    repo: https://github.com/oneroskilfu/ireva-app
    region: oregon
    dockerContext: ./
    dockerfilePath: ./server/Dockerfile
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://ireva_db_user:fCTmNyo2YqM8iWDPEDKf6cq75LxuRAad@dpg-d0p5pomuk2gs739ana70-a/ireva_db
      - key: REDIS_URL
        value: redis://red-d0p5uummcj7s73dqk1lg:6379
      - key: JWT_SECRET
        value: fba4762e52ab29cbec388fd6908192ab6e836d16baa10bd720ceffcf19627c24119eb6a4b70da2ee85eba036da5d003d3f94bcf06266b48df7681823a174240e
      - key: NODE_ENV
        value: production