services:
  - type: web
    name: iREVA-app
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: server/Dockerfile
    buildFilter:
      paths:
        - client/**
        - server/**
    healthCheckPath: /api/health
    autoDeploy: true
